### ISSUE TITLE
ConnectionStatus property doesn't set

### ISSUE THREAD

**Issue by asc793** [connio/octopus-issues#190]
I have created a device from ConnectedDevice profie then connected to broker via its apikey. But there isn't any value has set to ConnectionStatus property. Also there is nothing as initial value,  shouldn't the value be as "offline" when a device created but not connected yet?

```
Account : _acc_495269316522393674
Key : _key_495269325625889848
Secret : c5c864117881405fa8e9c7ec8cf3ece0
```

```
deviceId:_dev_495402035740363485
mqttbroker
address : 172.26.41.102
clientId : _???_af5f0f2d99
user : _key_495402035746194393
pass : fc89a042f89d4137974a3485f76f1f6d
```

**Comment by bmrb** [comment]
> Also there is nothing as initial value, shouldn't the value be as "offline" when a device created but not connected yet?

This is expected behaviour (please let me know if documentation is misleading). Some devices uses only REST endpoint to write data, so Connio doesn't speculate on connection status until the device  explicitly gets connected to the platform.

> I have created a device from ConnectedDevice profie then connected to broker via its apikey. But there isn't any value has set to ConnectionStatus property. 

This is a separate issue. If you use device id as `MQTT client Id`, device API Key id as username, and device API key secret as password, this device should be set to online. 

What do you see on the UI (try port 80) as device connection state after the connection is successfully complete. Also you might try this out:

`GET {{url}}/v3/data/devices/{{DEV_ID}}/state?header=false&meta=false&properties=connectionstatus,connectioninfo&methods=&alerts=`

**Comment by asc793** [comment]
Sorry, I have missed to set client id as device id. Now I have observed that the value has set as online. And I got the point that why the initial value doesn't set. Thank you.
You can close the issue.
