### ISSUE TITLE
How to see "disabled" attribute device method 

### ISSUE THREAD

**Issue by volkansk** [connio/octopus-issues#194]
We can change status -Enable/Disable- device method but don't response in method details. I couldn't find the details in the document. How can i see the method is disable?

**Enable/Disable device method,Response:**
```
{
    "meta": {
        "id": "_mtd_496011844794149917",
        "accountId": "_acc_494140327607417274",
        "ownerId": "_dpf_496011833092912768",
        "name": "mtd_d9mthmfo",
        "friendlyName": "fname d9mthmfo",
        "inherited": false,
        "qualifiedName": "dpf_d9mthmfo$mtd_d9mthmfo",
        "description": "desc d9mthmfo",
        "tags": [
            "t1",
            "t2"
        ],
        "access": "public",
        "inputTTL": "5 seconds",
        "methodImpl": {
            "funcBody": "return value == 1 ? \"running\" : \"stopped\";",
            "script": "javascript"
        },
        "locked": false,
        "dateCreated": "2018-11-16T08:46:59.626Z",
        "dateModified": "2018-11-16T08:46:59.626Z"
    },
    **"disabled": true**
}
```

**List methods, Response**
```
{
    "id": "_mtd_496011844794149917",
    "accountId": "_acc_494140327607417274",
    "ownerId": "_dpf_496011833092912768",
    "name": "mtd_d9mthmfo",
    "friendlyName": "fname d9mthmfo",
    "inherited": false,
    "qualifiedName": "dpf_d9mthmfo$mtd_d9mthmfo",
    "description": "desc d9mthmfo",
    "tags": [
        "t1",
        "t2"
    ],
    "access": "public",
    "inputTTL": "5 seconds",
    "methodImpl": {
        "funcBody": "return value == 1 ? \"running\" : \"stopped\";",
        "script": "javascript"
    },
    "locked": false,
    "dateCreated": "2018-11-16T08:46:59.626Z",
    "dateModified": "2018-11-16T08:46:59.626Z"
}
```

**Comment by bmrb** [comment]
Method entity is different then method instance. Method entity (method details) is belong to app/device profile, and method instance is belong to a device or app state. This gives us the capability to enable/disable a method per device/app. 

This is analog to what we have with any Object-Oriented language where Class (Profile) is the definition, Object (Device or App) that each instance gets its own materialized version (kinda). 

In that sense, all operations under `../v3/devices/` are about method definitions and definition does not have enable/disable attribute since there is no way to enable/disable a method at profile level - what would we? If you don't want to use a method, simply delete it from the profile.

On the other hand,  `.../v3/data/devices/:id/state` is about device instance, and each device instance has its own instance of methods where you can enable/disable per device. The rationale behind this design is security. If the developer writes a long lasting script or something throwing exception every time it is invoked, system has capabilty to disable this method so the consecutive requests doesn't affect the system performance and sanity.

I am going to put this into documentation. Thanks for pointing out.

Close this issue if you feel this is satisfactory.

**Comment by volkansk** [comment]
Thank you for the information.
